//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlashRoll.Web.RollReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RollReference.IRoll")]
    public interface IRoll {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoll/SlashRoll", ReplyAction="http://tempuri.org/IRoll/SlashRollResponse")]
        int SlashRoll(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRollChannel : SlashRoll.Web.RollReference.IRoll, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RollClient : System.ServiceModel.ClientBase<SlashRoll.Web.RollReference.IRoll>, SlashRoll.Web.RollReference.IRoll {
        
        public RollClient() {
        }
        
        public RollClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RollClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RollClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RollClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SlashRoll(string username) {
            return base.Channel.SlashRoll(username);
        }
    }
}
